version: 0.0
os: linux
files:
  - source: app
  - source: scripts
  - source: migrations
  - source: nginx_config.conf
  - source: requirements.txt
  - source: Dockerfile
  - source: docker-compose.yaml
    destination: /
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      runas: root
