services:
  chat-api:
    build: ./
    image: giovanebmilani/csg5-chatacademico-python
    environment:
      - DB_ENGINE=postgresql+psycopg2
      - DB_HOST=10.5.0.6
      - DB_USERNAME=postgres
      - DB_PASSWORD=1234
      - DB_PORT=5432
      - DB_NAME=postgres
    ports:
      - '80:5000'
    volumes:
      - './:/src/:rw'
    stdin_open: true
    tty: true
    networks:
      vpc:
        ipv4_address: 10.5.0.5

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgres
    networks:
      vpc:
        ipv4_address: 10.5.0.6

networks:
  vpc:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1

volumes:
  db: