name: csg5-chatacademico-python
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Install AWS CLI 2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Terraform infra provisioning
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.3.7"
      
      - run: terraform init
      - run: terraform apply --auto-approve

      - name: AWS Deploy push
        run: |
          aws deploy push \
          --application-name csg5-chatacademico-application \
          --ignore-hidden-files \
          --s3-location s3://csg5-chatacademico-codedeploy-deployments/csg5-chatacademico-deployment-${{ github.sha }}.zip \
          --source .

      - name: AWS Create Deployment
        run: |
          aws deploy create-deployment \
          --application-name csg5-chatacademico-application \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name csg5-chatacademico-deployment-group \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=csg5-chatacademico-codedeploy-deployments,key=csg5-chatacademico-deployment-${{ github.sha }}.zip,bundleType=zip \
